https://pandas.pydata.org/pandas-docs/stable/

In [2]:
import pandas as pd #this will import pandas into your workspace
import numpy as np

In [3]:
#Numpy arrays

In [4]:
arr = np.array([1,2,3])

In [5]:
arr

array([1, 2, 3])

In [7]:
my_mat = [[1,2,3],[2,3,4],[5,6,7]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [2, 3, 4],
       [5, 6, 7]])

In [10]:
np.arange(0,11,2) #2 is step-size

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros((5,5)) #we pass a tuple

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.linspace(0,5,10) #last argument is number of digits

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.random.rand(5,5,5)

array([[[0.77868215, 0.50684548, 0.64559438, 0.5321125 , 0.89710004],
        [0.20799271, 0.87854009, 0.12287826, 0.75555813, 0.68946129],
        [0.31807978, 0.0854525 , 0.11529567, 0.07140382, 0.06530531],
        [0.29984828, 0.14953946, 0.50595333, 0.31472936, 0.37328355],
        [0.36179305, 0.92558289, 0.77225498, 0.08103969, 0.43146699]],

       [[0.19467631, 0.03084617, 0.07713473, 0.02326203, 0.51065378],
        [0.2756339 , 0.62836548, 0.8446211 , 0.57002403, 0.65445147],
        [0.41378076, 0.52509521, 0.50350336, 0.931294  , 0.92669014],
        [0.79706274, 0.04950273, 0.09211174, 0.69229897, 0.96702449],
        [0.17833457, 0.73726613, 0.40611577, 0.85132658, 0.98842764]],

       [[0.75815894, 0.18481221, 0.43282533, 0.36984956, 0.20185802],
        [0.44185337, 0.68205791, 0.40728922, 0.6213109 , 0.33699438],
        [0.61774864, 0.55546159, 0.34386651, 0.53555989, 0.04863948],
        [0.86577392, 0.05542342, 0.07605586, 0.43870183, 0.21101399],
        [0.65424

In [20]:
np.random.rand(5,5)

array([[0.13685907, 0.2478238 , 0.35622892, 0.63394344, 0.79409084],
       [0.99931714, 0.64236947, 0.38795612, 0.76699768, 0.35531852],
       [0.78483605, 0.81520164, 0.40569538, 0.1761772 , 0.07978619],
       [0.74801997, 0.61072012, 0.34505517, 0.41353203, 0.31320994],
       [0.09901988, 0.24925931, 0.96015653, 0.54638044, 0.498481  ]])

In [18]:
np.random.rand(5)

array([0.93285984, 0.41207838, 0.53884988, 0.77169859, 0.9092032 ])

In [21]:
#random number having uniform distribution from 0 to 1

In [22]:
#what if I want normal distribution

In [25]:
np.random.randn(4,4)
               

array([[-1.40270468,  0.36245462,  1.06365796, -0.04723841],
       [-0.6392069 , -0.03914628, -1.85664744,  1.38409452],
       [-0.03755265,  1.35531911, -0.01809173, -0.66176669],
       [ 1.01365961, -0.75793341, -0.39924049,  0.45058624]])

In [27]:
np.random.randint(1,100,10)

array([46, 74, 11, 32, 44, 93, 91, 93, 33,  7])

In [28]:
arr = np.arange(25)

In [37]:
ranarr = np.random.randint(0,50,10)
print(ranarr)

[31 30 47 21  2 11 36 44 33 10]


In [30]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
ranarr

array([12, 11, 17, 32,  5, 29, 26, 16, 48, 45])

In [32]:
ranarr.max()

48

In [33]:
ranarr.min()

5

In [38]:
ranarr.argmax() #index location of maximum value

2

In [36]:
ranarr.argmin()

4

In [39]:
arr.shape #it's  a 1D vector

(25,)

In [40]:
arr = arr.reshape(5,5)
arr.shape

(5, 5)

In [41]:
arr.dtype

dtype('int32')

In [42]:
from numpy.random import randint

In [43]:
randint(2,10)

5

In [44]:
randint(2,500)

306

In [ ]:
randint()

In [45]:
import numpy as np
arr = np.arange(0,11)

In [46]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
arr[8:]

array([ 8,  9, 10])

In [48]:
arr[:5]

array([0, 1, 2, 3, 4])

In [50]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
#Numpy array broadcasts


In [51]:
arr[0:5]=100


In [52]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [53]:
arr = np.arange(0,11)

In [54]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
slice_of_arr = arr[0:6]

In [56]:
slice_of_arr[:] = 99

In [57]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [58]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [ ]:
#Reason why numpy does that is to cope up to avoid memory issues with very large arrays


In [ ]:
#if you actually want a copy and not a reference to the original array
#you can do it actually specifically specifying  a copy

In [62]:
arr_copy = arr.copy()
print(arr_copy, arr)

[99 99 99 99 99 99  6  7  8  9 10] [99 99 99 99 99 99  6  7  8  9 10]


In [60]:
arr_copy[:] = 100

In [61]:
print(arr_copy, arr)

[100 100 100 100 100 100 100 100 100 100 100] [99 99 99 99 99 99  6  7  8  9 10]


In [ ]:
#2 D array or matrix

In [64]:
arr_2d = np.array([[5,10,15],[20,25,30],[22,2,34]])

In [65]:
arr_2d[0]

array([ 5, 10, 15])

In [ ]:
#You can grab the array elements by two method
arr_2d[1][2] # arr_2d[1,2], second is better. Less chances to be wrong

In [66]:
arr_2d[1,2]

30

In [69]:
#Using the second method
t = arr_2d[:2,1:]
print(t)

[[10 15]
 [25 30]]


In [68]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [22,  2, 34]])

In [70]:
#to get all rows
arr_2d[0,:]

array([ 5, 10, 15])

In [71]:
#conditional selection

arr = np.arange(1,11)

In [74]:
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [75]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [76]:
arr_2d[t]

IndexError: index 10 is out of bounds for axis 0 with size 3

In [78]:
arr[arr>5]


array([ 6,  7,  8,  9, 10])

In [79]:
arr_2d[arr_2d > 5]

array([10, 15, 20, 25, 30, 22, 34])

In [80]:
arr[arr < 3]

array([1, 2])

In [ ]:
#Create a new 2d array and have values in it and then reshape it


In [82]:
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [83]:
arr_2d[1:3,(1,3,5)]#Give it a tuple

array([[11, 13, 15],
       [21, 23, 25]])

In [84]:
new_arr = arr_2d.copy()
new_arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [88]:
modif = np.array([[499,500],[499,500]])
new_arr[2:4,(1,2)] = modif
new_arr

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20, 499, 500,  23,  24,  25,  26,  27,  28,  29],
       [ 30, 499, 500,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

In [94]:
import numpy as np
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [91]:
arr += arr
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [92]:
arr -= arr
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [95]:
arr = np.arange(0,11)
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [96]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [ ]:
#That means it will broadcast to every elements

In [97]:
1/0

ZeroDivisionError: division by zero

In [ ]:
#numpy won't  give you this array. It will give nan, not an error but a warning

In [98]:
arr/arr

<ipython-input-98-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
#for a number divided by 0, it would give inf

In [99]:
1/arr

<ipython-input-99-016353831300>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [100]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [101]:
arr ** (1/2)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [103]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [105]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [106]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [107]:
np.max(arr)

10

In [108]:
arr.max()

10

In [109]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [110]:
np.log(arr)

<ipython-input-110-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [ ]:
https://numpy.org/doc/stable/reference/ufuncs.html

In [ ]:
##pandas##

##DATA STRUCTURES IN PANDAS
There are two basic data structures in pandas: Series and DataFrame



In [ ]:
#Creating a python series object
#Series is a datatype in python, it's represented as a table with only 1 column and autoassigned row id's

In [111]:
import numpy as np
import pandas as pd


In [115]:
labels = ['a','b','c']
my_data = [10,20,30]
arr = np.array(my_data)
d = {'a':10,'b':20,'c':30}

In [113]:
pd.Series(data = my_data)

0    10
1    20
2    30
dtype: int64

In [116]:
pd.Series(data = my_data, index = labels)

a    10
b    20
c    30
dtype: int64

In [117]:
#OR
pd.Series(my_data,labels)

a    10
b    20
c    30
dtype: int64

In [118]:
pd.Series(arr)
        

0    10
1    20
2    30
dtype: int32

In [119]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [120]:
pd.Series(labels)

0    a
1    b
2    c
dtype: object

In [121]:
pd.Series(data = [sum,print,len])



0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [122]:
ser1 = pd.Series([1,2,3,4],['USA','USSR','Japan','Germany'])

In [123]:
ser2 = pd.Series([1,2,3,4],['USA','USSR','Italy','Germany'])

In [124]:
ser1['USA']

1

In [127]:
ser3 = pd.Series(data = labels)
ser3

0    a
1    b
2    c
dtype: object

In [128]:
ser3[1]

'b'

In [129]:
ser1

USA        1
USSR       2
Japan      3
Germany    4
dtype: int64

In [130]:
ser1 + ser2

Germany    8.0
Italy      NaN
Japan      NaN
USA        2.0
USSR       4.0
dtype: float64

In [131]:
np.random.seed(101)

In [132]:
df = pd.DataFrame(np.random.randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])

In [133]:
df


W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [137]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [138]:
type(df['W'])

pandas.core.series.Series

In [139]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
#dataframe is just a bunch of series that shares the same index


In [140]:
df.W

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [141]:
df[['W','Z']]

W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [151]:
df['new'] = df['W'] + df['Y']

In [150]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [145]:
df.drop('new',axis = 1) #axis is important

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [152]:
#Now let's see what happenened to our dataframe
df


W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [154]:
df.drop('new',axis = 1, inplace = True) #inplace is necessary to not accidentally loose the important info

In [148]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [155]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [156]:
df.drop('E') 

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

In [158]:
df.shape #see the result, now you got the info as to why rows are 0 and columns are 1?

(5, 4)

In [159]:
df[['Z','X']]

Z         X
A  0.503826  0.628133
B  0.605965 -0.319318
C -0.589001  0.740122
D  0.955057 -0.758872
E  0.683509  1.978757

In [ ]:
# SElecting rows using loc and iloc

In [160]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [161]:
df.loc['A']

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [ ]:
#this means not only columns are series but rows are as well

In [163]:
df.loc['C']

W   -2.018168
X    0.740122
Y    0.528813
Z   -0.589001
Name: C, dtype: float64

In [164]:
df.iloc[2]

W   -2.018168
X    0.740122
Y    0.528813
Z   -0.589001
Name: C, dtype: float64

In [165]:
df.loc['B','Y']

-0.8480769834036315

In [166]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [167]:
df.loc[['A','B'],['X','Y']]

X         Y
A  0.628133  0.907969
B -0.319318 -0.848077

In [168]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [169]:
df > 0

W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [173]:
booldf = df>0

In [174]:
df[booldf]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [172]:
df[df>0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [175]:
df['W']>0

A     True
B     True
C    False
D     True
E     True
Name: W, dtype: bool

In [176]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [178]:
df[df['W']>0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [179]:
df[df['Z']<0]

W         X         Y         Z
C -2.018168  0.740122  0.528813 -0.589001

In [180]:
resultdf = df[df['W']>0]
resultdf

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [182]:
#use less steps
df[df['W']>0]['X']


A    0.628133
B   -0.319318
D   -0.758872
E    1.978757
Name: X, dtype: float64

In [183]:
boolser = df['W']>0

In [185]:
boolser

A     True
B     True
C    False
D     True
E     True
Name: W, dtype: bool

In [188]:
#using multiple condition
df[df['W']>0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [190]:
df[(df['W']>0) & (df['Y']>1)]

W         X         Y         Z
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
#inpandas use & and | instead of and and or coz these handles True and False type stuff. Will get confused 
#in case there are whole series

In [191]:
df[(df['W']>0) | (df['Y']>1)]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [192]:
df.reset_index() #index reset 

index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [193]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
#for permanent do inplace = True
df.reset_index(inplace = True)

In [194]:
newind = 'CA NY WY OR CO'.split()

In [195]:
newind

['CA', 'NY', 'WY', 'OR', 'CO']

In [196]:
df['States'] = newind

In [197]:
df

W         X         Y         Z States
A  2.706850  0.628133  0.907969  0.503826     CA
B  0.651118 -0.319318 -0.848077  0.605965     NY
C -2.018168  0.740122  0.528813 -0.589001     WY
D  0.188695 -0.758872 -0.933237  0.955057     OR
E  0.190794  1.978757  2.605967  0.683509     CO

In [198]:
#setting an index
df.set_index('States')

W         X         Y         Z
States                                        
CA      2.706850  0.628133  0.907969  0.503826
NY      0.651118 -0.319318 -0.848077  0.605965
WY     -2.018168  0.740122  0.528813 -0.589001
OR      0.188695 -0.758872 -0.933237  0.955057
CO      0.190794  1.978757  2.605967  0.683509

In [ ]:
#it's still not inplace = True. take care while doing that as it will be permanent changing of a column as an index

In [206]:
#Index levels
from numpy.random import *
outside1 = 'G1 G2 G1 G2 G1 G2'
outside = outside1.split()
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside)) #to make tuple pairs
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [201]:
outside

['G1', 'G2', 'G1', 'G2', 'G1', 'G2']

In [202]:
inside

[1, 2, 3, 1, 2, 3]

In [203]:
hier_index

MultiIndex([('G1', 1),
            ('G2', 2),
            ('G1', 3),
            ('G2', 1),
            ('G1', 2),
            ('G2', 3)],
           )

In [208]:
df = pd.DataFrame(randn(6,2),hier_index,['A','B'])
df

A         B
G1 1 -0.497104 -0.754070
G2 2 -0.943406  0.484752
G1 3 -0.116773  1.901755
G2 1  0.238127  1.996652
G1 2 -0.993263  0.196800
G2 3 -1.136645  0.000366

In [ ]:
#This is a multilevel data

In [210]:
print(df)

             A         B
G1 1 -0.497104 -0.754070
G2 2 -0.943406  0.484752
G1 3 -0.116773  1.901755
G2 1  0.238127  1.996652
G1 2 -0.993263  0.196800
G2 3 -1.136645  0.000366


In [211]:
df.loc['G1']

A         B
1 -0.497104 -0.754070
3 -0.116773  1.901755
2 -0.993263  0.196800

In [212]:
df.loc['G1'].loc[1]

A   -0.497104
B   -0.754070
Name: 1, dtype: float64

In [213]:
df.index.names

FrozenList([None, None])

In [214]:
df.index.names = ['Groups', 'Num']

In [215]:
df

A         B
Groups Num                    
G1     1   -0.497104 -0.754070
G2     2   -0.943406  0.484752
G1     3   -0.116773  1.901755
G2     1    0.238127  1.996652
G1     2   -0.993263  0.196800
G2     3   -1.136645  0.000366

In [216]:
df.loc['G2'].loc[2]['B']

0.48475164718163294

In [217]:
df.xs(1,level = 'Num') #cross-section

A         B
Groups                    
G1     -0.497104 -0.754070
G2      0.238127  1.996652

In [1]:
import numpy as np
import pandas as pd

In [8]:
d = {'A':[1,2,np.nan], 'B':[5,np.nan,np.nan], 'C': [1,2,3]}

In [9]:
df = pd.DataFrame(d)

In [10]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [11]:
df.dropna()

A    B  C
0  1.0  5.0  1

In [12]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [13]:
df.dropna(axis = 1)

C
0  1
1  2
2  3

In [14]:
df.dropna(thresh= 2)

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [ ]:
#Let's replace the na values


In [15]:
df.fillna(value = 'FILL VALUE')

A           B  C
0           1           5  1
1           2  FILL VALUE  2
2  FILL VALUE  FILL VALUE  3

In [ ]:
#LET'S FILL WITH MEAN

In [16]:
df['A'].fillna(value = df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [17]:
#groupby

In [18]:

data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}

In [20]:
df = pd.DataFrame(data)

In [21]:
df

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [22]:
df.groupby('Company')

In [23]:
byComp = df.groupby('Company')

In [24]:
byComp

In [25]:
byComp.mean()

Sales
Company       
FB       296.5
GOOG     160.0
MSFT     232.0

In [26]:
byComp.std()

Sales
Company            
FB        75.660426
GOOG      56.568542
MSFT     152.735065

In [27]:
byComp.sum()

Sales
Company       
FB         593
GOOG       320
MSFT       464

In [28]:
byComp.sum().loc['FB']

Sales    593
Name: FB, dtype: int64

In [29]:
df.groupby('Company').sum().loc['FB']

Sales    593
Name: FB, dtype: int64

In [30]:
df.groupby('Company').count()

Person  Sales
Company               
FB            2      2
GOOG          2      2
MSFT          2      2

In [31]:
df.groupby('Company').min() #string max would be just alphabetically

Person  Sales
Company                
FB          Carl    243
GOOG     Charlie    120
MSFT         Amy    124

In [32]:
df.groupby('Company').describe()

Sales                                                        
        count   mean         std    min     25%    50%     75%    max
Company                                                              
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [34]:
df.groupby('Company').describe().transpose()['FB']

Sales  count      2.000000
       mean     296.500000
       std       75.660426
       min      243.000000
       25%      269.750000
       50%      296.500000
       75%      323.250000
       max      350.000000
Name: FB, dtype: float64

In [35]:
#merging, joining and concatenating

In [ ]:
Series1 = pd.Series([10,20,30,40]) #we have used a list to create a series.
print(Series1)

0    10
1    20
2    30
3    40
dtype: int64


Printing the values that are there in the series

In [ ]:
Series1.values

array([10, 20, 30, 40])

In [ ]:
mylist  = [1,2,3,'today',12.34]

In arrays, the elements are stored in continuous memory location. 
List is not like that.


Anything which is an array, same datatype and extremely faster than the lists.

Figuring out the index numbers that are there in the series

In [ ]:
k = list(Series1.index) #This would print the starting index and ending index
print(k)

[0, 1, 2, 3]


Specifying custom index values rather than the default ones provided, you can do so using the following command

In [ ]:
series2 = pd.Series([10,20,30,45,55], index = ['one','two','three','four','five'])

In [ ]:
print(series2)

one      10
two      20
three    30
four     45
five     55
dtype: int64
